### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by endrift** [xerpi/libftpvita#26]
I'd like to make a small fork of libftpvita for a project I want to work on but without a license specified I can't really do that.

If you could specify a license I'd really appreciate it.

**Comment by xerpi** [comment]
Sure I can do that! Which license do you think it would be a good fit, maybe the MIT License or a kind of GPL?

**Comment by endrift** [comment]
That's ultimately up to you, but MIT would be perfectly fine by me. So long as it's not GPL or AGPL I can still use it.

**Comment by xerpi** [comment]
Done! cab592331ed2dbda33199dd48fc5092e2e29806d
