### ISSUE TITLE
error “C2-12828-1″ 

### ISSUE THREAD

**Issue by cysin** [xerpi/libftpvita#3]
I download the binary from http://wololo.net/downloads/index.php/download/8317 but got error “C2-12828-1″ . So would you please investigate it?

**Comment by antonizoon** [comment]
Can confirm, when using **PSM Dev Assistant for Unity 1.05**.

I was able to get Hello World.elf not working, but not FTPVita. Maybe it just needs to be updated and retested for Unity?

**Comment by antonizoon** [comment]
Ok, found the solution. FTPVita needs to be recompiled to target PSM Unity. https://github.com/xerpi/FTPVita/issues/4

**Comment by xerpi** [comment]
Fixed with 1a8338472a5cca6419e3e086a0a545b6a0ed5ecd.
