### ISSUE TITLE
Recompile FTPVita for Unity (Solves Error C2-12828-1)

### ISSUE THREAD

**Issue by antonizoon** [xerpi/libftpvita#4]
Rejuvenate for PSM Unity has finally been released! However, [FTPVita needs to be recompiled to target it](http://wololo.net/talk/viewtopic.php?f=113&t=43856), otherwise we get `error C2-12828-1` for PSM Unity users. Please create a Unity version, FTPVita is the keystone app for Rejuvenate.

Here's an unofficial working recompiled version for PSM Unity: https://www.mediafire.com/?bqusw94uc571wp1

**Comment by xerpi** [comment]
Should it be recompiled with different CFLAGS? Like without -O2

**Comment by antonizoon** [comment]
Not sure, I'm just reporting the bug. You might want to ask `skogaby`, he's the guy who made this patched edition:

http://wololo.net/talk/memberlist.php?mode=viewprofile&u=60424
https://github.com/skogaby/

**Comment by isshoujuuzou** [comment]
No one interested in it? It looks like there ain't enough people using PSM Dev Assist for Unity >: Would I be able to recompile it even though I'm not that much experienced with C Language? lol

**Comment by xerpi** [comment]
I've already solved this "bug" on 1a8338472a5cca6419e3e086a0a545b6a0ed5ecd.
